### ISSUE TITLE
very slow when use fp16 trt engine for square_inference

### ISSUE THREAD

**Issue by bug-developer021** [NVIDIA-AI-IOT/yolov5_gpu_optimization#3]
I test on tesla T4 gpu, it cost about 20ms per image at shape (1, 3, 640, 640) on inference and batchedNMS.
On the other hand, I use https://github.com/ultralytics/yolov5/blob/v6.1/export.py to build  a none dynamic shape trt engine,  and use https://github.com/ultralytics/yolov5/blob/v6.1/detect.py to infer. It cost about 4.4ms for inference, 2.2ms for NMS. I don't know what happend

I export yolov5s.pt to fp16 trt engine

**Comment by Tyler-D** [comment]
How do you profile the inference time ?

**Comment by bug-developer021** [comment]
> How do you profile the inference time ?

I simply use time.time() to record 
```python
def square_inference(engine, img_root, output_img_root, input_size=640, jlist=None):
    with engine.create_execution_context() as context:
        context.set_binding_shape(0, (1, 3, input_size, input_size))
        new_shape = (input_size, input_size)
        inputs, outputs, bindings, stream = allocate_buffers(engine, context)

        # calculate the speed of preprocess and inference per image
        dt, seen = [0.0, 0.0], 0

        for img_name in sorted(os.listdir(img_root)):
            if os.path.splitext(img_name)[-1] not in ['.jpg', '.png', '.jpeg']:
                continue
            img_path = os.path.join(img_root, img_name)
            if jlist is not None:
                img_id = int(img_name.split(".")[0])
            else:
                img_id = None
            
            t1 = time.time()
            images, orig_img = load_images_cv(img_path, new_shape)
            ratio_pad = None
            batch_images = images
            # Hard Coded For explicit_batch and the ONNX model's batch_size = 1
            batch_images = batch_images[np.newaxis, :, :, :]
            t2 = time.time()
            dt[0] += t2 - t1
            outputs_shape, outputs_data = do_inference(batch=batch_images, context=context,
                                                        bindings=bindings, inputs=inputs,
                                                        outputs=outputs, stream=stream)
            t3 = time.time()
            dt[1] += t3 - t2
            results = decode(keep_k = outputs_data["BatchedNMS"],
                                boxes = outputs_data["BatchedNMS_1"],
                                scores = outputs_data["BatchedNMS_2"],
                                cls_id = outputs_data["BatchedNMS_3"])

            seen += 1
            # visualize the bbox
            draw_bbox_cv(orig_img, images, os.path.join(output_img_root, img_name),
                         results[0], image_id=img_id, jlist=jlist, ratio_pad=ratio_pad)
        t = tuple(x / seen * 1E3 for x in dt)  # speeds per image
        print(f'Preprocess: %.2f ms, Inference: %.2f ms  per image at shape {(1,3, input_size, input_size)}' % t)
```

**Comment by Tyler-D** [comment]
OK. Your profiling is not a fair comparision. If you want to know the `GPU backbone infer time + GPU NMS time` as in ultralytics code's `inference time` and `NMS time`,  You should add the timer in the `do_inference` like this (notice the `t1`, `t2` and `stream.synchronize`):

```
def do_inference(batch, context, bindings, inputs, outputs, stream):
    batch_size = batch.shape[0]
    assert len(inputs) == 1
    inputs[0].host = np.ascontiguousarray(batch, dtype=np.float32)
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
    stream.synchronize()
    t1 = time.time()
    context.execute_async(batch_size=batch_size, bindings=bindings, stream_handle=stream.handle)
    stream.synchronize()
    t2 = time.time()
    print(f"inf time: {t2 - t1}\n")
    [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
    stream.synchronize()

    outputs_dict = {}
    outputs_shape = {}
    for out in outputs:
        outputs_dict[out.binding_name] = np.reshape(out.host, out.shape)
        outputs_shape[out.binding_name] = out.shape

    return outputs_shape, outputs_dict
```

**Comment by bug-developer021** [comment]
> OK. Your profiling is not a fair comparision. If you want to know the `GPU backbone infer time + GPU NMS time` as in ultralytics code's `inference time` and `NMS time`, You should add the timer in the `do_inference` like this (notice the `t1`, `t2` and `stream.synchronize`):
> 
> ```
> def do_inference(batch, context, bindings, inputs, outputs, stream):
>     batch_size = batch.shape[0]
>     assert len(inputs) == 1
>     inputs[0].host = np.ascontiguousarray(batch, dtype=np.float32)
>     [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
>     stream.synchronize()
>     t1 = time.time()
>     context.execute_async(batch_size=batch_size, bindings=bindings, stream_handle=stream.handle)
>     stream.synchronize()
>     t2 = time.time()
>     print(f"inf time: {t2 - t1}\n")
>     [cuda.memcpy_dtoh_async(out.host, out.device, stream) for out in outputs]
>     stream.synchronize()
> 
>     outputs_dict = {}
>     outputs_shape = {}
>     for out in outputs:
>         outputs_dict[out.binding_name] = np.reshape(out.host, out.shape)
>         outputs_shape[out.binding_name] = out.shape
> 
>     return outputs_shape, outputs_dict
> ```

Hi @Tyler-D !  I follow your instuction to change  code , But the  result is still almost 20ms per image at shape (1, 3, 640, 640). It's much slow than  ultralytics code's inference time and NMS time.

But when I use `trtexec` to test model performance
```shell
/usr/src/tensorrt/bin/trtexec  \
--loadEngine=my_yolov5s.engine \
--verbose \
--fp16 \
--shapes=images:1x3x640x640 \
> result-FP16.txt
```

the median of metrics as below:

metics|BatchedNMSDynamic_TRT engine<br>infer+nms|ultralytics engine<br>only infer|
:-:|:-:|:-:|
Latency|3.97021 ms|4.08145 ms|
End-to-End Host Latency|6.70715 ms|4.73285 ms|
Enqueue Time|1.27597 ms|0.95929 ms|
H2D Latency|0.563791 ms|0.316406 ms|
GPU Compute Time|3.45068 ms| 2.41992 ms|
D2H Latency|0.0100889 ms|1.34198 ms|


It's much better

**Comment by Tyler-D** [comment]
OK. Good to know that. 

Not sure what happened to your env. I also tested YOLOV5s from my side on a V100. And the do_inference infer time is similar to trtexec GPU latency. (Slightly worse: ~350 FPS VS ~378 FPS).

**Comment by bug-developer021** [comment]
> OK. Good to know that.
> 
> Not sure what happened to your env. I also tested YOLOV5s from my side on a V100. And the do_inference infer time is similar to trtexec GPU latency. (Slightly worse: ~350 FPS VS ~378 FPS).


Gratitude! I increased the number of images of  my test dataset, And the BatchedNMSDynamic_TRT engine's infer speed is 5.4ms per image. Finally close to ultralytics engine's speed.

**Comment by bug-developer021** [comment]
Add more test data may be useful

**Comment by Tyler-D** [comment]
You should see more improvement with batch size increasing. Refer to this table: https://github.com/NVIDIA-AI-IOT/yolov5_gpu_optimization#performancemap-summary

What test data do you expect ? Thanks for suggestion.

**Comment by bug-developer021** [comment]
> You should see more improvement with batch size increasing. Refer to this table: https://github.com/NVIDIA-AI-IOT/yolov5_gpu_optimization#performancemap-summary
> 
> What test data do you expect ? Thanks for suggestion.

I think Concurrency and throughput are enough
