### ISSUE TITLE
Why the use of v1 and v2 is separated in do_inference function

### ISSUE THREAD

**Issue by YoungjaeDev** [NVIDIA-AI-IOT/yolov5_gpu_optimization#8]
I have a question about this part.

https://github.com/NVIDIA-AI-IOT/yolov5_gpu_optimization/blob/b54cd6cf33740cf60a40069752bfdf57152b287f/tensorrt-sample/trt_inference/engine.py#L271-L304

In the end, the difference between the two seems to be a little different when input batch_size or not and output parsing parte. By the way, is there a reason why the time of use should be separated due to the difference in performance (Here, it seems to be used differently when it's rect, square) ?

**Comment by Tyler-D** [comment]
There should be no difference with the same input shape. But only v2 (and the v3 in TRT > 8.5) can support dynamic shape.

**Comment by YoungjaeDev** [comment]
@Tyler-D Thank you!
